name: weather-router
channels:
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - pip
  - pip:
    - gpxpy
    - openmeteo-requests
    - openmeteo-sdk
    - rdp
    - pytest
variables:
prefix:
platforms:
  - linux-64
  - osx-arm64
  - win-64
  - osx-64
